/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package HospitalFourManagementSystem;

import Doctor.Doctor;
import GPAppointment.GPAppointment;
import Login.Login;
import Patient.Patient;
import java.awt.event.ActionEvent;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

//import java.awt.*;
//import java.awt.print.*;
//import javax.swing.*;

import java.awt.print.PrinterException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author user
 */
public class HospitalFourManagementSystem extends javax.swing.JFrame {
private JFrame frame;
    /**
     * Creates new form HospitalFourManagementSystem
     */
    public HospitalFourManagementSystem() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jbtnUpdate = new javax.swing.JButton();
        jbtnDelete = new javax.swing.JButton();
        jbtnPatient = new javax.swing.JButton();
        jbtnGpAppointment = new javax.swing.JButton();
        jbtnRest = new javax.swing.JButton();
        jbtnPrescription = new javax.swing.JButton();
        jbtnLogin = new javax.swing.JButton();
        jbtnExit = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtextPrescription = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jCmbNameTablets = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jtxtRef = new javax.swing.JTextField();
        jtxtDose = new javax.swing.JTextField();
        jtxtNumberTablets = new javax.swing.JTextField();
        jtxtLot = new javax.swing.JTextField();
        jtxtIssuedDate = new javax.swing.JTextField();
        jtxtExpDate = new javax.swing.JTextField();
        jtxtDailyDose = new javax.swing.JTextField();
        jtxtPossibleSideEffects = new javax.swing.JTextField();
        jtxtFurtherInformation = new javax.swing.JTextField();
        jtxtStorageAdvice = new javax.swing.JTextField();
        jtxtDrivingUsingMachines = new javax.swing.JTextField();
        jtxtHowtoUseMedication = new javax.swing.JTextField();
        jtxtPatientID = new javax.swing.JTextField();
        jtxtDoctorNHSNo = new javax.swing.JTextField();
        jtxtPatientName = new javax.swing.JTextField();
        jtxtPatientAddress = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jtxtDateofBirth = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1400, 800));
        setPreferredSize(new java.awt.Dimension(1400, 800));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 60)); // NOI18N
        jLabel1.setText("Hospital Management System");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1250, 80));

        jPanel5.setBackground(new java.awt.Color(0, 0, 0));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbtnUpdate.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtnUpdate.setText("Update");
        jbtnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnUpdateActionPerformed(evt);
            }
        });
        jPanel5.add(jbtnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 120, 40));

        jbtnDelete.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtnDelete.setText("Delete");
        jbtnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDeleteActionPerformed(evt);
            }
        });
        jPanel5.add(jbtnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, 90, 40));

        jbtnPatient.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtnPatient.setText("Patient");
        jbtnPatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPatientActionPerformed(evt);
            }
        });
        jPanel5.add(jbtnPatient, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 20, 140, 40));

        jbtnGpAppointment.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtnGpAppointment.setText("GP Appointment");
        jbtnGpAppointment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnGpAppointmentActionPerformed(evt);
            }
        });
        jPanel5.add(jbtnGpAppointment, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 20, -1, 40));

        jbtnRest.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtnRest.setText("Reset");
        jbtnRest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnRestActionPerformed(evt);
            }
        });
        jPanel5.add(jbtnRest, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 20, 100, 40));

        jbtnPrescription.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtnPrescription.setText("Prescription");
        jbtnPrescription.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPrescriptionActionPerformed(evt);
            }
        });
        jPanel5.add(jbtnPrescription, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 20, 140, 40));

        jbtnLogin.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtnLogin.setText("Login");
        jbtnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnLoginActionPerformed(evt);
            }
        });
        jPanel5.add(jbtnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 20, 90, 40));

        jbtnExit.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtnExit.setText("Exit");
        jbtnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnExitActionPerformed(evt);
            }
        });
        jPanel5.add(jbtnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 20, -1, 40));

        jButton9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton9.setText("Print");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 20, 80, 40));

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton3.setText("Doctor");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, 120, 40));

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 460, 1250, 80));

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtextPrescription.setColumns(20);
        jtextPrescription.setRows(5);
        jScrollPane1.setViewportView(jtextPrescription);

        jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 350, 360));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 90, 370, 450));

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 45)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Patient Prescription");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, -1, 60));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 900, 70));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Name of tablet");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        jCmbNameTablets.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jCmbNameTablets.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Make a Selection", "Panadol", "Brufen", "Ceptrine", "Headex" }));
        jCmbNameTablets.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCmbNameTabletsActionPerformed(evt);
            }
        });
        getContentPane().add(jCmbNameTablets, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 180, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Reference No:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Dose (mg)");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Further Information:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 180, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("How to Use Medication");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 270, -1, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("Possible Side Effect:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, 190, 30));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setText("Daily Dose");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, -1, 30));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setText("NHS Number:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 330, -1, 30));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setText("Date of Birth");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 400, -1, 30));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setText("Patient Name:");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 370, -1, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel14.setText("Exp Date");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, -1, 30));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel15.setText("LOT:");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, -1, 30));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel16.setText("Issued Date:");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, -1, 30));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel17.setText("Number of Tablets:");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, -1, -1));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel18.setText("Patient ID:");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 300, -1, 30));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel19.setText("Storage Advice:");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 210, -1, 30));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel20.setText("Patient Address:");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 430, -1, 30));

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel21.setText("Driving & Using Machine:");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 240, 230, -1));

        jtxtRef.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtRef.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtRefActionPerformed(evt);
            }
        });
        getContentPane().add(jtxtRef, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 220, 190, -1));

        jtxtDose.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtDose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtDoseActionPerformed(evt);
            }
        });
        getContentPane().add(jtxtDose, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 250, 190, -1));

        jtxtNumberTablets.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(jtxtNumberTablets, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 280, 190, -1));

        jtxtLot.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(jtxtLot, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 310, 190, -1));

        jtxtIssuedDate.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(jtxtIssuedDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 340, 190, -1));

        jtxtExpDate.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(jtxtExpDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 370, 190, -1));

        jtxtDailyDose.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(jtxtDailyDose, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 400, 190, -1));

        jtxtPossibleSideEffects.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(jtxtPossibleSideEffects, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 430, 190, -1));

        jtxtFurtherInformation.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(jtxtFurtherInformation, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 180, 200, -1));

        jtxtStorageAdvice.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(jtxtStorageAdvice, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 210, 200, 30));

        jtxtDrivingUsingMachines.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(jtxtDrivingUsingMachines, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 240, 200, -1));

        jtxtHowtoUseMedication.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(jtxtHowtoUseMedication, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 270, 200, -1));

        jtxtPatientID.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(jtxtPatientID, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 300, 200, -1));

        jtxtDoctorNHSNo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(jtxtDoctorNHSNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 330, 200, -1));

        jtxtPatientName.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(jtxtPatientName, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 362, 200, 30));

        jtxtPatientAddress.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(jtxtPatientAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 420, 200, 30));

        jTable1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name of Tablet", "Reference Number", "Dose (mg)", "Number of Tablets", "LOT", "Issued Date", "Exp Date", "Daily Dose", "Possible side Effects", "Further Information", "Storage Advice", "Administration", "Driving and Using Medication", "How to Use medication", "Patient ID", "Doctor NHS No", "Date of Birth", "Patient Address"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 550, 1250, -1));

        jtxtDateofBirth.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(jtxtDateofBirth, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 390, 200, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtxtDoseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtDoseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtDoseActionPerformed

    private void jbtnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnExitActionPerformed
        frame =new JFrame();
        if (JOptionPane.showConfirmDialog(frame, "Confirm if you want to exit","Hospital Management Systems",
               JOptionPane.YES_NO_OPTION ) == JOptionPane.YES_NO_OPTION ){ 
            System.exit(0);
        }       
    }//GEN-LAST:event_jbtnExitActionPerformed
private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {                                         
       Doctor iDoctor = new Doctor();
       iDoctor.setVisible(true);
    }                                        
    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        try{
            jtextPrescription.print();
        }catch (PrinterException ex){
            Logger.getLogger(HospitalFourManagementSystem.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jbtnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnUpdateActionPerformed
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object []{jCmbNameTablets.getSelectedItem().toString(),
            jtxtRef.getText(), jtxtDose.getText(), jtxtNumberTablets.getText(),
            jtxtLot.getText(), jtxtIssuedDate.getText(), jtxtExpDate.getText(), 
            jtxtDailyDose.getText(), jtxtPossibleSideEffects.getText(),  
            jtxtFurtherInformation.getText(), jtxtStorageAdvice.getText(), 
            jtxtDrivingUsingMachines.getText(), jtxtHowtoUseMedication.getText(), 
            jtxtPatientID.getText(), jtxtDoctorNHSNo.getText(), jtxtPatientName.getText(), 
            jtxtDateofBirth.getText(), jtxtPatientAddress.getText()
        });
    }//GEN-LAST:event_jbtnUpdateActionPerformed

    private void jbtnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDeleteActionPerformed
       DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
       if(jTable1.getSelectedRow() ==-1){
        if(jTable1.getRowCount() ==0){
            
            JOptionPane.showMessageDialog(null, "No data to delete" , "Hospital Management Systems",
                JOptionPane.OK_OPTION);
            }else{
            JOptionPane.showMessageDialog(null, "Select a row to delete" , "Hospital Management Systems",
                JOptionPane.OK_OPTION);
        }   
       }else{
           model.removeRow(jTable1.getSelectedRow());
       }
    }//GEN-LAST:event_jbtnDeleteActionPerformed

    private void jbtnPatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPatientActionPerformed
       Patient iPatient = new Patient();
       iPatient.setVisible(true);
    }//GEN-LAST:event_jbtnPatientActionPerformed

    private void jbtnGpAppointmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnGpAppointmentActionPerformed
        GPAppointment iGPAppointment = new GPAppointment();
       iGPAppointment.setVisible(true);
    }//GEN-LAST:event_jbtnGpAppointmentActionPerformed
     private void jbtnLoginActionPerformed(java.awt.event.ActionEvent evt) {                                          
        Login iLogin = new Login();
        iLogin.setVisible(true);   // TODO add your handling code here:
    }                                         
    private void jbtnRestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnRestActionPerformed
            jtxtRef.setText("");
            jtxtDose.setText("");
            jtxtNumberTablets.setText("");
            jtxtLot.setText("");
            jtxtIssuedDate.setText("");
            jtxtExpDate.setText("");
            jtxtDailyDose.setText("");
            
            jtxtPossibleSideEffects.setText("");
            jtxtFurtherInformation.setText("");
            jtxtStorageAdvice.setText("");
            jtxtDrivingUsingMachines.setText("");
            jtxtHowtoUseMedication.setText("");
            jtxtPatientID.setText("");
            jtxtDoctorNHSNo.setText("");
            jtxtPatientName.setText("");
            jtxtDateofBirth.setText("");
            jtxtPatientAddress.setText("");
            jtextPrescription.setText("");
            jCmbNameTablets.getModel().setSelectedItem("Make a Selection");
    }//GEN-LAST:event_jbtnRestActionPerformed

    private void jbtnPrescriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPrescriptionActionPerformed
        String Qty1 = (jtxtRef.getText());
        String Qty2 = (jtxtDose.getText());
        String Qty3 = (jtxtNumberTablets.getText());
        String Qty4 = (jtxtLot.getText());
        String Qty5 = (jtxtDailyDose.getText());
        String Qty6 = (jtxtPossibleSideEffects.getText());
        String Qty7 = (jtxtFurtherInformation.getText());
        String Qty8 = (jtxtHowtoUseMedication.getText());
        String Qty9 = (jtxtPatientID.getText());
        String Qty10 = (jtxtPatientAddress.getText());
        String Qty11 = (jtxtPatientName.getText());
        String Qty12 = (jtxtDateofBirth.getText());
        String Qty13 = "";
        
            if (jCmbNameTablets.getSelectedItem().equals("Panadol"))
        {
            Qty13 = "Panadol";            
        }
            else if (jCmbNameTablets.getSelectedItem().equals("Brufen"))
        {
            Qty13 = "Brufen";            
        }
            else if (jCmbNameTablets.getSelectedItem().equals("Ceptrine"))
        {
            Qty13 = "Ceptrine";            
        }
            else if (jCmbNameTablets.getSelectedItem().equals("Headex"))
        {
            Qty13 = "Headex";            
        }
         
        jtextPrescription.setText("");
        jtextPrescription.append("\t\n\tFendo Hospital Management Systems\n"
                + "\nPatient Name:\t\t" + Qty11
                + "\nDate of Birth:\t\t" + Qty12
                + "\nPatient Adress:\t\t" + Qty10
                +   "\nPrescription:\t\t" + Qty13
                + "\nReference No:\t\t" + Qty1
                + "\nDose (mg):\t\t" + Qty2
                + "\nNumber of Tablets:\t" + Qty3
                + "\nLOT:\t\t" + Qty4
                + "\nDaily Dose:\t\t" + Qty5
                + "\nPossible Side Effects:\t" + Qty6
                + "\nFurther Information:\t" + Qty7
                + "\nHow to use Medication:\t" + Qty8
                + "\nPatient ID:\t\t" + Qty9
                + "\n\n\tPatient Instruction we have introduced a \n\tfree text confirmation\n\t"
                                + "TEXT REMINDERS FOR APPOINTMENT");
        
    }//GEN-LAST:event_jbtnPrescriptionActionPerformed
  
    private void jtxtRefActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtRefActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtRefActionPerformed
    private void jCmbNameTabletsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCmbNameTabletsActionPerformed
        if (jCmbNameTablets.getSelectedItem().equals("Panadol"))
        {
            jtxtRef.setText("Pan45357");
            jtxtDose.setText("2");
            jtxtNumberTablets.setText("32");
            jtxtLot.setText("2424567");
            jtxtIssuedDate.setText("24/04/2025");
            jtxtExpDate.setText("23/06/2026");
            jtxtDailyDose.setText("4");
            
            jtxtPossibleSideEffects.setText("Sleepy");
            jtxtFurtherInformation.setText("Place Dispensary");
            jtxtStorageAdvice.setText("Less Than 20 degrees celcius");
            jtxtDrivingUsingMachines.setText("No");
            jtxtHowtoUseMedication.setText("Use water Only");
            jtxtPatientID.setText("34125216");
            jtxtDoctorNHSNo.setText("14247");
        }
/*
    }//GEN-LAST:event_jCmbNameTabletsActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // THIS LINE OF CODE DISTURBED ME AND THEREFORE I CREATED A NEW ONE, ON TOP, I COMMENTED IT OUT BECAUSE EACH TIME IT CAME HERE
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jbtnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnLoginActionPerformed
               // TODO add your handling code here:
    }//GEN-LAST:event_jbtnLoginActionPerformed
// 
*/ 
else if (jCmbNameTablets.getSelectedItem().equals("Brufen"))
        { 
            jtxtRef.setText("Bru45357");
            jtxtDose.setText("500");
            jtxtNumberTablets.setText("30");
            jtxtLot.setText("B94567");
            jtxtIssuedDate.setText("20/04/2025");
            jtxtExpDate.setText("15/06/2026");
            jtxtDailyDose.setText("2");
            
            jtxtPossibleSideEffects.setText("Dizziness");
            jtxtFurtherInformation.setText("Place Dispensary");
            jtxtStorageAdvice.setText("Less Than 30 degrees celcius");
            jtxtDrivingUsingMachines.setText("No");
            jtxtHowtoUseMedication.setText("Use water Only");
            jtxtPatientID.setText("P4125216");
            jtxtDoctorNHSNo.setText("54297");
    } 
else if (jCmbNameTablets.getSelectedItem().equals("Ceptrine"))
      {
            jtxtRef.setText("Cep853");
            jtxtDose.setText("500");
            jtxtNumberTablets.setText("16");
            jtxtLot.setText("F94567");
            jtxtIssuedDate.setText("19/04/2025");
            jtxtExpDate.setText("14/06/2026");
            jtxtDailyDose.setText("2");
            
            jtxtPossibleSideEffects.setText("Feeling Sick");
            jtxtFurtherInformation.setText("Place Dispensary");
            jtxtStorageAdvice.setText("Less Than 25 degrees celcius");
            jtxtDrivingUsingMachines.setText("No");
            jtxtHowtoUseMedication.setText("Use water Only");
            jtxtPatientID.setText("G4125216");
            jtxtDoctorNHSNo.setText("86297");
      }
 else if (jCmbNameTablets.getSelectedItem().equals("Headex"))
      {
            jtxtRef.setText("75336");
            jtxtDose.setText("5");
            jtxtNumberTablets.setText("28");
            jtxtLot.setText("Q94567");
            jtxtIssuedDate.setText("18/04/2025");
            jtxtExpDate.setText("13/06/2026");
            jtxtDailyDose.setText("1");
            
            jtxtPossibleSideEffects.setText("Confussion");
            jtxtFurtherInformation.setText("Might delay Result");
            jtxtStorageAdvice.setText("Cool Dry Place");
            jtxtDrivingUsingMachines.setText("Yes");
            jtxtHowtoUseMedication.setText("Use water Only");
            jtxtPatientID.setText("R41252");
            jtxtDoctorNHSNo.setText("4262467");
    
    }
 else if (jCmbNameTablets.getSelectedItem().equals("Make a Selection"))
      {
            jtxtRef.setText("");
            jtxtDose.setText("");
            jtxtNumberTablets.setText("");
            jtxtLot.setText("");
            jtxtIssuedDate.setText("");
            jtxtExpDate.setText("");
            jtxtDailyDose.setText("");
            
            jtxtPossibleSideEffects.setText("");
            jtxtFurtherInformation.setText("");
            jtxtStorageAdvice.setText("");
            jtxtDrivingUsingMachines.setText("");
            jtxtHowtoUseMedication.setText("");
            jtxtPatientID.setText("");
            jtxtDoctorNHSNo.setText("");
}
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HospitalFourManagementSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HospitalFourManagementSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HospitalFourManagementSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HospitalFourManagementSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HospitalFourManagementSystem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox<String> jCmbNameTablets;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jbtnDelete;
    private javax.swing.JButton jbtnExit;
    private javax.swing.JButton jbtnGpAppointment;
    private javax.swing.JButton jbtnLogin;
    private javax.swing.JButton jbtnPatient;
    private javax.swing.JButton jbtnPrescription;
    private javax.swing.JButton jbtnRest;
    private javax.swing.JButton jbtnUpdate;
    private javax.swing.JTextArea jtextPrescription;
    private javax.swing.JTextField jtxtDailyDose;
    private javax.swing.JTextField jtxtDateofBirth;
    private javax.swing.JTextField jtxtDoctorNHSNo;
    private javax.swing.JTextField jtxtDose;
    private javax.swing.JTextField jtxtDrivingUsingMachines;
    private javax.swing.JTextField jtxtExpDate;
    private javax.swing.JTextField jtxtFurtherInformation;
    private javax.swing.JTextField jtxtHowtoUseMedication;
    private javax.swing.JTextField jtxtIssuedDate;
    private javax.swing.JTextField jtxtLot;
    private javax.swing.JTextField jtxtNumberTablets;
    private javax.swing.JTextField jtxtPatientAddress;
    private javax.swing.JTextField jtxtPatientID;
    private javax.swing.JTextField jtxtPatientName;
    private javax.swing.JTextField jtxtPossibleSideEffects;
    private javax.swing.JTextField jtxtRef;
    private javax.swing.JTextField jtxtStorageAdvice;
    // End of variables declaration//GEN-END:variables
}
